dist: xenial
addons:
  apt:
    packages:
    - libxinerama-dev
    - libasound2-dev
    - mesa-common-dev
    - libgl-dev
    - libxi-dev
    - zip

language: node_js
node_js: 10

env:
  - BUILD_TARGET=debug-html5 BUILD_OPTS=""
  - BUILD_TARGET=linux BUILD_OPTS="--compile"
  - BUILD_TARGET=html5 BUILD_OPTS=""

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/593f9ec49210b8694911
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  # - nvm install v8
  # - git clone --branch $TRAVIS_BRANCH https://github.com/haxeui/haxeui-core.git --depth=1
  - git clone https://github.com/haxeui/haxeui-core.git --depth=1
  - haxelib dev haxeui-core haxeui-core

install:
  - haxelib install hscript
  - haxelib dev haxeui-kha $TRAVIS_BUILD_DIR

script:
  - git clone https://github.com/sh-dave/haxeui-templates.git --depth=1
  - cd haxeui-templates/kha/skeleton
  - git clone --recursive --single-branch --depth=1 https://github.com/Kode/Kha.git
  - node Kha/make $BUILD_TARGET $BUILD_OPTS
